version: "2"
linters:
  enable:
    - gosec
    - revive
    - errcheck
  settings:
    errcheck:
      exclude-functions:
        - os.Remove
    godot:
      scope: toplevel
      exclude:
        - '^todo:'
        - '^fixme:'
        - //
    gosec:
      excludes:
        - G402
    revive:
      enable-all-rules: true
      rules:
        - name: nested-structs
          disabled: true
        - name: redundant-import-alias
          severity: warning
          disabled: true
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 4
          severity: warning
          disabled: false
        - name: function-length
          arguments:
            - 80
            - 200
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
        - name: cyclomatic
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 40
          severity: warning
          disabled: false
        - name: argument-limit
          arguments:
            - 8
          severity: warning
          disabled: false
        - name: file-header
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - myFunction
          severity: warning
          disabled: true
        - name: comment-spacings
          severity: warning
          disabled: true
        - name: package-comments
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: exported
          severity: warning
          disabled: false
        - name: useless-break
          severity: warning
          disabled: true
        - name: import-shadowing
          severity: warning
          disabled: true
        - name: deep-exit
          severity: warning
          disabled: true
        - name: var-naming
          severity: warning
          disabled: true
        - name: var-declaration
          severity: warning
          disabled: true
        - name: confusing-naming
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    paths:
      - filelink
      - audit
      - addin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$