# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint

on: [push]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: 0.27.1 # https://github.com/actions/setup-go/issues/746
          cache-dependency-path: go.tool.sum
      - name: execute linter
        run: go tool -modfile=go.tool.mod golangci-lint run
